-- MySQL Script generated by MySQL Workbench
-- Dom 26 Fev 2017 00:29:59 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dreamteam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dreamteam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dreamteam` DEFAULT CHARACTER SET utf8 ;
USE `dreamteam` ;

-- -----------------------------------------------------
-- Table `dreamteam`.`tblfuncao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dreamteam`.`tblfuncao` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dreamteam`.`tblogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dreamteam`.`tblogin` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tblfuncao_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_tblogin_tblfuncao1_idx` (`tblfuncao_codigo` ASC),
  CONSTRAINT `fk_tblogin_tblfuncao1`
    FOREIGN KEY (`tblfuncao_codigo`)
    REFERENCES `dreamteam`.`tblfuncao` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dreamteam`.`tbcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dreamteam`.`tbcategoria` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dreamteam`.`tbproduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dreamteam`.`tbproduto` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `qtd` VARCHAR(45) NOT NULL,
  `tbcategoria_codigo` INT NOT NULL,
  `tblogin_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_tbproduto_tbcategoria_idx` (`tbcategoria_codigo` ASC),
  INDEX `fk_tbproduto_tblogin1_idx` (`tblogin_codigo` ASC),
  CONSTRAINT `fk_tbproduto_tbcategoria`
    FOREIGN KEY (`tbcategoria_codigo`)
    REFERENCES `dreamteam`.`tbcategoria` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbproduto_tblogin1`
    FOREIGN KEY (`tblogin_codigo`)
    REFERENCES `dreamteam`.`tblogin` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dreamteam`.`tbtributos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dreamteam`.`tbtributos` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dreamteam`.`tbtributos_has_tbproduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dreamteam`.`tbtributos_has_tbproduto` (
  `tbtributos_codigo` INT NOT NULL,
  `tbproduto_codigo` INT NOT NULL,
  PRIMARY KEY (`tbtributos_codigo`, `tbproduto_codigo`),
  INDEX `fk_tbtributos_has_tbproduto_tbproduto1_idx` (`tbproduto_codigo` ASC),
  INDEX `fk_tbtributos_has_tbproduto_tbtributos1_idx` (`tbtributos_codigo` ASC),
  CONSTRAINT `fk_tbtributos_has_tbproduto_tbtributos1`
    FOREIGN KEY (`tbtributos_codigo`)
    REFERENCES `dreamteam`.`tbtributos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbtributos_has_tbproduto_tbproduto1`
    FOREIGN KEY (`tbproduto_codigo`)
    REFERENCES `dreamteam`.`tbproduto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dreamteam`.`tborcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dreamteam`.`tborcamento` (
  `codigo` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  `tblogin_codigo` INT NOT NULL,
  `venda` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_tborcamento_tblogin1_idx` (`tblogin_codigo` ASC),
  CONSTRAINT `fk_tborcamento_tblogin1`
    FOREIGN KEY (`tblogin_codigo`)
    REFERENCES `dreamteam`.`tblogin` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dreamteam`.`tborcamento_has_tbproduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dreamteam`.`tborcamento_has_tbproduto` (
  `tborcamento_codigo` INT NOT NULL,
  `tbproduto_codigo` INT NOT NULL,
  PRIMARY KEY (`tborcamento_codigo`, `tbproduto_codigo`),
  INDEX `fk_tborcamento_has_tbproduto_tbproduto1_idx` (`tbproduto_codigo` ASC),
  INDEX `fk_tborcamento_has_tbproduto_tborcamento1_idx` (`tborcamento_codigo` ASC),
  CONSTRAINT `fk_tborcamento_has_tbproduto_tborcamento1`
    FOREIGN KEY (`tborcamento_codigo`)
    REFERENCES `dreamteam`.`tborcamento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tborcamento_has_tbproduto_tbproduto1`
    FOREIGN KEY (`tbproduto_codigo`)
    REFERENCES `dreamteam`.`tbproduto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `dreamteam`.`tblfuncao`
-- -----------------------------------------------------
START TRANSACTION;
USE `dreamteam`;
INSERT INTO `dreamteam`.`tblfuncao` (`codigo`, `nome`) VALUES (1, 'Administrador');
INSERT INTO `dreamteam`.`tblfuncao` (`codigo`, `nome`) VALUES (2, 'Funcionario');

COMMIT;


-- -----------------------------------------------------
-- Data for table `dreamteam`.`tblogin`
-- -----------------------------------------------------
START TRANSACTION;
USE `dreamteam`;
INSERT INTO `dreamteam`.`tblogin` (`codigo`, `nome`, `sobrenome`, `email`, `senha`, `tblfuncao_codigo`) VALUES (DEFAULT, 'Administrador', 'adm', 'adm@adm', '123456', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `dreamteam`.`tbcategoria`
-- -----------------------------------------------------
START TRANSACTION;
USE `dreamteam`;
INSERT INTO `dreamteam`.`tbcategoria` (`codigo`, `nome`, `descricao`) VALUES (DEFAULT, 'Categoria A', 'Categoria A');
INSERT INTO `dreamteam`.`tbcategoria` (`codigo`, `nome`, `descricao`) VALUES (DEFAULT, 'Categoria B', 'Categoria B');
INSERT INTO `dreamteam`.`tbcategoria` (`codigo`, `nome`, `descricao`) VALUES (DEFAULT, 'Categoria C', 'Categoria C');

COMMIT;

